spring.application.name=ordermanagement

server.port=8008

logging.file.name=logs/application.log

# ===============================
#   Database Configuration
# ===============================

# PostgreSQL connection URL
spring.datasource.url=jdbc:postgresql://localhost:5432/ordermanagement

# PostgreSQL username
spring.datasource.username=postgres

# PostgreSQL password
spring.datasource.password=admin@123

# tell sping data we are using -postgress
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
#   JPA / Hibernate Settings
# ===============================

spring.jpa.hibernate.ddl-auto=validate

# Show SQL queries in console
spring.jpa.show-sql=true

# Specify the Hibernate dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=my-super-secret-key-my-super-secret-key-256-bit-long
jwt.expiration=3600000